using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

internal class CkIdsCodeGenerator
{
    /// <summary>
    /// Returns the singleton instance of <see cref="CkIdsCodeGenerator"/>
    /// </summary>
    public static readonly CkIdsCodeGenerator Instance = new();
    
    public string Generate(string ns, CkModelId ckModelId, ICollection<CkTypeDto>? ckTypes, 
        ICollection<CkAttributeDto>? ckAttributes, ICollection<CkAssociationRoleDto>? ckAssociationRoles)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit model {ckModelId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {ckModelId.ModelId}CkIds");
        sb.AppendLine("{");
        
        sb.AppendLine($"    public static readonly CkModelId {ckModelId.ModelId}ModelId = new(\"{ckModelId.SemanticVersionedFullName}\");");

        if (ckTypes != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Types");

            foreach (var ckTypeDto in ckTypes.OrderBy(x=> x.TypeId.TypeId))
            {
                sb.AppendLine($"    public static readonly CkTypeId {ckTypeDto.TypeId.TypeId} = new(\"{ckTypeDto.TypeId.SemanticVersionedFullName}\");");
            }
        }
        
        if (ckAttributes != null)
        {
            foreach (var ckAttributeDto in ckAttributes.OrderBy(x=> x.AttributeId.AttributeId))
            {
                sb.AppendLine();
                sb.AppendLine("    // Attributes");
                
                sb.AppendLine($"    public static readonly CkAttributeId {ckAttributeDto.AttributeId.AttributeId} = new(\"{ckAttributeDto.AttributeId.SemanticVersionedFullName}\");");
            }
        }
                
        if (ckAssociationRoles != null)
        {
            foreach (var ckAssociationRoleDto in ckAssociationRoles.OrderBy(x=> x.AssociationRoleId.RoleId))
            {
                sb.AppendLine();
                sb.AppendLine("    // Associations");
                
                sb.AppendLine($"    public static readonly CkAssociationRoleId {ckAssociationRoleDto.AssociationRoleId.RoleId} = new(\"{ckAssociationRoleDto.AssociationRoleId.SemanticVersionedFullName}\");");
            }
        }
        
        sb.AppendLine("}");
        
        return sb.ToString();
    }
}