using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

/// <summary>
/// Generates code for a CK type
/// </summary>
public class CkTypeCodeGenerator : ICkTypeCodeGenerator
{
    /// <summary>
    /// Returns the singleton instance of <see cref="CkTypeCodeGenerator"/>
    /// </summary>
    public static readonly CkTypeCodeGenerator Instance = new();

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public bool Equals(ICkTypeCodeGenerator? other)
    {
        return other is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode() => GetType().GetHashCode();

    /// <inheritdoc />
    public string Generate(string ns, CkModelId modelId, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
    {
        var ckBaseType = "";
        if (ckType.DerivedFromCkTypeId != null)
        {
            ckBaseType = $" : Rt{ckType.DerivedFromCkTypeId.Value.ModelId.ModelId.MakeClassName()}" +
                         $"{ckType.DerivedFromCkTypeId.Value.Key.TypeId.MakeClassName()}";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit type {ckType.TypeId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"[CkId({modelId.ModelId.MakeClassName()}CkIds.ModelId, {modelId.ModelId.MakeClassName()}CkIds.{ckType.TypeId.TypeId.MakeClassName()})]");
        sb.AppendLine($"public partial class Rt{modelId.ModelId.MakeClassName()}{ckType.TypeId.TypeId.MakeClassName()}{ckBaseType}");
        sb.AppendLine("{");
        if (ckType.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckType.Attributes)
            {
                GenerateProperty(ckTypeAttributeDto, sb, cacheTenantId, cacheService);
            }
        }

        if (ckType.Associations != null)
        {
            foreach (var ckTypeAssociationDto in ckType.Associations)
            {
                GenerateNavigation(ckTypeAssociationDto, sb, cacheTenantId, cacheService);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateNavigation(CkTypeAssociationDto ckTypeAssociationDto, StringBuilder sb, string cacheTenantId, ICkCacheService cacheService)
    {
        //var ckAssociationRoleGraph = cacheService.GetCkAssociationRole(cacheTenantId, ckTypeAssociationDto.CkRoleId);

        sb.AppendLine($"  // Unsupported by Generator: {ckTypeAssociationDto.CkRoleId}->{ckTypeAssociationDto.TargetCkTypeId}");
    }

    private static void GenerateProperty(CkTypeAttributeDto ckTypeAttributeDto, StringBuilder sb, string cacheTenantId, ICkCacheService cacheService)
    {
        var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
        
        switch (ckAttributeGraph.ValueType)
        {
            case AttributeValueTypesDto.String:
                sb.AppendLine($"  public string? {ckTypeAttributeDto.AttributeName}");
                sb.AppendLine("  {");
                sb.AppendLine("      get => GetAttributeStringValueOrDefault(nameof(" + ckTypeAttributeDto.AttributeName + "));");
                sb.AppendLine("      set => SetAttributeValue(nameof(" + ckTypeAttributeDto.AttributeName + "), AttributeValueTypes.String, value);");
                sb.AppendLine("  }");
                break;
            case AttributeValueTypesDto.Int:
                sb.AppendLine($"  public long? {ckTypeAttributeDto.AttributeName}");
                sb.AppendLine("  {");
                sb.AppendLine("      get => GetAttributeValueOrDefault<long>(nameof(" + ckTypeAttributeDto.AttributeName + "));");
                sb.AppendLine("      set => SetAttributeValue(nameof(" + ckTypeAttributeDto.AttributeName + "), AttributeValueTypes.Int, value);");
                sb.AppendLine("  }");
                break;
            case AttributeValueTypesDto.DateTime:
                sb.AppendLine($"  public System.DateTime? {ckTypeAttributeDto.AttributeName}");
                sb.AppendLine("  {");
                sb.AppendLine("      get => GetAttributeValueOrDefault<System.DateTime>(nameof(" + ckTypeAttributeDto.AttributeName + "));");
                sb.AppendLine("      set => SetAttributeValue(nameof(" + ckTypeAttributeDto.AttributeName + "), AttributeValueTypes.DateTime, value);");
                sb.AppendLine("  }");
                break;
            case AttributeValueTypesDto.Double:
                sb.AppendLine($"  public double? {ckTypeAttributeDto.AttributeName}");
                sb.AppendLine("  {");
                sb.AppendLine("      get => GetAttributeValueOrDefault<double>(nameof(" + ckTypeAttributeDto.AttributeName + "));");
                sb.AppendLine("      set => SetAttributeValue(nameof(" + ckTypeAttributeDto.AttributeName + "), AttributeValueTypes.Double, value);");
                sb.AppendLine("  }");
                break;
            case AttributeValueTypesDto.Boolean:
                sb.AppendLine($"  public bool? {ckTypeAttributeDto.AttributeName}");
                sb.AppendLine("  {");
                sb.AppendLine("      get => GetAttributeValueOrDefault<bool>(nameof(" + ckTypeAttributeDto.AttributeName + "));");
                sb.AppendLine("      set => SetAttributeValue(nameof(" + ckTypeAttributeDto.AttributeName + "), AttributeValueTypes.Boolean, value);");
                sb.AppendLine("  }");
                break;
            case AttributeValueTypesDto.BinaryLinked:
                sb.AppendLine($"  // Unsupported by Generator: {ckTypeAttributeDto.AttributeName} (Type: {ckAttributeGraph.ValueType})");
                break;
        }
    }
}