using System.Globalization;
using Meshmakers.Common.CommandLineParser;
using Meshmakers.Common.CommandLineParser.Commands;
using Meshmakers.Octo.ConstructionKit.Compiler.Commands.Implementations.GenerateDocsTools;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.Serialization;
using Meshmakers.Octo.ConstructionKit.Engine.Resolvers;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Meshmakers.Octo.ConstructionKit.Compiler.Commands.Implementations;

public class GenerateDocsCommand : Command<OctoToolOptions>
{
    private readonly IModelResolver _modelResolver;
    private readonly ICkYamlSerializer _ckYamlSerializer;
    private readonly IArgument _filePathArg;
    private readonly IArgument _docusaurusDestinationPathArg;
    private readonly IMermaidGenerator _mermaidGenerator;
    private readonly IContentGenerator _contentGenerator;


    public GenerateDocsCommand(ILogger<GenerateDocsCommand> logger, IModelResolver modelResolver, ICkYamlSerializer ckYamlSerializer,
        IOptions<OctoToolOptions> options, IMermaidGenerator mermaidGenerator, IContentGenerator contentGenerator)
        : base(logger, "generateDocs", "Generates docs from an compiled construction kit library", options)
    {
        _modelResolver = modelResolver;
        _ckYamlSerializer = ckYamlSerializer;
        _mermaidGenerator = mermaidGenerator;
        _contentGenerator = contentGenerator;

        _filePathArg = CommandArgumentValue.AddArgument("f", "file",
            ["Path of compiled construction kit model file"], true, 1);

        //use Docs folder for autogenerated Docusaurus Sidebar Functionality
        _docusaurusDestinationPathArg = CommandArgumentValue.AddArgument("o", "output", ["Path of Docusaurus Docs Directory"], true, 1);
        
    }

    public override async Task Execute()
    {
        Logger.LogInformation("Creating documentation for construction kit model");

        var filePath = CommandArgumentValue.GetArgumentScalarValue<string>(_filePathArg);
        var docusaurusPath = CommandArgumentValue.GetArgumentScalarValue<string>(_docusaurusDestinationPathArg);
        
        await using var stream = File.OpenRead(filePath);

        OperationResult operationResult = new(); // operation result is used to collect errors and warnings.
        var compiledModelRoot = await _ckYamlSerializer.DeserializeCompiledModelRootAsync(stream, filePath, operationResult);

        // Evaluates current ConstructionKit
        if (compiledModelRoot.Types != null)
        {
            foreach (var ckCompiledTypeDto in compiledModelRoot.Types)
            {
                Logger.LogInformation("{TypeId}", ckCompiledTypeDto.TypeId.ToString(CultureInfo.InvariantCulture));
            }
        }

        // Resolves Dependencies
        var originFileResolver = new OriginFileResolver(filePath);
        var resolvedTypes = await _modelResolver.ResolveAsync(compiledModelRoot, originFileResolver, operationResult);

        //ID Determines Position in File Tree   
        await _mermaidGenerator.GenerateMermaidTextOutput(resolvedTypes, docusaurusPath, compiledModelRoot.ModelId);
        await _contentGenerator.GenerateVersionHistory(docusaurusPath, compiledModelRoot.ModelId);

        await _contentGenerator.GenerateAttributesMarkdownTable(Logger, resolvedTypes, docusaurusPath, compiledModelRoot.ModelId);
        await _contentGenerator.GenerateEnumsMarkdownTable(Logger, resolvedTypes, docusaurusPath, compiledModelRoot.ModelId);
        await _contentGenerator.GenerateRecordsMarkdownTable(Logger, resolvedTypes, docusaurusPath, compiledModelRoot.ModelId);
        await _contentGenerator.GenerateTypesMarkdownTable(Logger, resolvedTypes, docusaurusPath, compiledModelRoot.ModelId);
        await _contentGenerator.GenerateAssociationRolesMarkdownTable(Logger, resolvedTypes, docusaurusPath, compiledModelRoot.ModelId);
    }
}