using Meshmakers.Common.CommandLineParser;
using Meshmakers.Common.CommandLineParser.Commands;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.Serialization;
using Meshmakers.Octo.ConstructionKit.Engine.Documentation;
using Meshmakers.Octo.ConstructionKit.Engine.Resolvers;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Meshmakers.Octo.ConstructionKit.Compiler.Commands.Implementations;

internal class GenerateDocsCommand : Command<OctoToolOptions>
{
    private readonly IModelResolver _modelResolver;
    private readonly ICkYamlSerializer _ckYamlSerializer;
    private readonly IArgument _modelSourcePathArg;
    private readonly IArgument _destinationPathArg;
    private readonly IArgument _versionNumberArg;
    private readonly IMermaidGenerator _mermaidGenerator;
    private readonly IContentGenerator _contentGenerator;
    private readonly ModeSelectionOptions _modeSelectionOptions;


    public GenerateDocsCommand(ILogger<GenerateDocsCommand> logger, IModelResolver modelResolver, ICkYamlSerializer ckYamlSerializer,
        IOptions<OctoToolOptions> options, IMermaidGenerator mermaidGenerator, IContentGenerator contentGenerator, 
        IOptions<ModeSelectionOptions> modeSelectionOptions)
        : base(logger, "generateDocs", "Generates docs from an compiled construction kit library", options)
    {
        _modelResolver = modelResolver;
        _ckYamlSerializer = ckYamlSerializer;
        _mermaidGenerator = mermaidGenerator;
        _contentGenerator = contentGenerator;
        _modeSelectionOptions = modeSelectionOptions.Value;

        _modelSourcePathArg = CommandArgumentValue.AddArgument("f", "file",
            ["Path of compiled construction kit model file"], true, 1);

        //use Docs folder for autogenerated Docusaurus Sidebar Functionality
        _destinationPathArg = CommandArgumentValue.AddArgument("o", "output", ["Path of Target Directory"], true, 1);

        _versionNumberArg = CommandArgumentValue.AddArgument("v", "version", ["Version Number of the Model that is Documented"], true, 1);

    }

    public override async Task Execute()
    {
        Logger.LogInformation("Creating documentation for construction kit model");

        var filePath = CommandArgumentValue.GetArgumentScalarValue<string>(_modelSourcePathArg);
        var outputPath = CommandArgumentValue.GetArgumentScalarValue<string>(_destinationPathArg);

        var versionNumber = CommandArgumentValue.GetArgumentScalarValue<string>(_versionNumberArg);
        
        await using var stream = File.OpenRead(filePath);

        OperationResult operationResult = new(); // operation result is used to collect errors and warnings.
        var compiledModelRoot = await _ckYamlSerializer.DeserializeCompiledModelRootAsync(stream, filePath, operationResult);

        // Resolves Dependencies
        var originFileResolver = new OriginFileResolver(filePath);
        var resolvedTypes = await _modelResolver.ResolveAsync(compiledModelRoot, originFileResolver, operationResult);

        //Docusaurus
        if (_modeSelectionOptions.DocumentationMode)
        {
            //ID Determines Position in File Tree   
            await _mermaidGenerator.GenerateMermaidTextOutput(resolvedTypes, outputPath, compiledModelRoot.ModelId);
            await _contentGenerator.GenerateVersionHistory(outputPath, compiledModelRoot.ModelId, versionNumber);

            await _contentGenerator.GenerateAttributesMarkdownTable(resolvedTypes, outputPath, compiledModelRoot.ModelId, versionNumber);
            await _contentGenerator.GenerateEnumsMarkdownTable(resolvedTypes, outputPath, compiledModelRoot.ModelId, versionNumber);
            await _contentGenerator.GenerateRecordsMarkdownTable(resolvedTypes, outputPath, compiledModelRoot.ModelId, versionNumber);
            await _contentGenerator.GenerateTypesMarkdownTable(resolvedTypes, outputPath, compiledModelRoot.ModelId, versionNumber);
            await _contentGenerator.GenerateAssociationRolesMarkdownTable(resolvedTypes, outputPath,
                compiledModelRoot.ModelId, versionNumber);
        }
        //ASP Net
        else
        {
            await using StreamWriter outputFile = new(Path.Combine(outputPath, "diagram.txt"));
            await _mermaidGenerator.GenerateMermaidDiagram(resolvedTypes, outputPath, compiledModelRoot.ModelId, outputFile);
        }
    }
}