using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.BlueprintCatalogs;
using Meshmakers.Octo.ConstructionKit.Contracts.BlueprintCatalogs.DataTransferObjects;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

/// <summary>
/// Emits an <c>IBlueprintEmbeddedSource</c> implementation + a DI extension method
/// (<c>AddBlueprint{Name}V{Major}</c>) for a single blueprint cache entry. Mirrors the role of
/// <see cref="CkEmbeddedModelDiGenerator" /> for CK models: a small, allocation-free pointer to
/// the assembly + resource namespace, registered as a singleton so the
/// <c>EmbeddedResourceBlueprintCatalog</c> can enumerate it at runtime.
/// </summary>
internal static class BlueprintEmbeddedSourceGenerator
{
    public static string Generate(string ns, BlueprintsCacheEntryDto entry, BlueprintId blueprintId)
    {
        var versionSuffix = $"V{blueprintId.Version.Major}";
        var className = $"{blueprintId.Name.MakeClassName()}{versionSuffix}BlueprintEmbeddedSource";
        var description = Escape(entry.Description ?? string.Empty);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.BlueprintCatalogs;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Generated <see cref=\"IBlueprintEmbeddedSource\" /> for blueprint {blueprintId.FullName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {className} : IBlueprintEmbeddedSource");
        sb.AppendLine("    {");
        sb.AppendLine($"        public BlueprintId BlueprintId {{ get; }} = new BlueprintId(\"{blueprintId.FullName}\");");
        sb.AppendLine($"        public string Description => \"{description}\";");
        sb.AppendLine($"        public Assembly Assembly => typeof({className}).Assembly;");
        sb.AppendLine($"        public string ResourceNamespace => \"{Escape(entry.ResourceNamespace)}\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // DI extension lives under Microsoft.Extensions.DependencyInjection so callers don't need
        // to import the generated namespace just to register the blueprint.
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            $"    /// Extension methods for registering the embedded blueprint {blueprintId.FullName} with the DI container.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class ServiceCollection{className}Extensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine(
            $"        /// Registers the {blueprintId.FullName} blueprint as an <see cref=\"Meshmakers.Octo.ConstructionKit.Contracts.BlueprintCatalogs.IBlueprintEmbeddedSource\" />.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine(
            $"        public static IServiceCollection AddBlueprint{blueprintId.Name.MakeClassName()}{versionSuffix}(");
        sb.AppendLine("            this IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine(
            $"            services.AddTransient<Meshmakers.Octo.ConstructionKit.Contracts.BlueprintCatalogs.IBlueprintEmbeddedSource, {ns}.{className}>();");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Escape(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
    }
}
