using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

public class CkClassMapGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="CkEmbeddedModelGenerator" />
    /// </summary>
    public static readonly CkClassMapGenerator Instance = new();

    public string Generate(string ns, List<CkCompiledTypeDto>? types, List<CkRecordDto>? records, CkModelId ckModelId)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.Services;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.RepositoryEntities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Represents a map of construction kit types and class types for model {ckModelId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public class {ckModelId.Name.MakeClassName()}CkTypeMap : ICkClassMap");
        sb.AppendLine("{");
        sb.AppendLine("   private readonly Dictionary<CkTypeId, Type> _typeMappings;");
        sb.AppendLine("   private readonly Dictionary<CkRecordId, Type> _recordMappings;");
        sb.AppendLine();
        sb.AppendLine($"   public {ckModelId.Name.MakeClassName()}CkTypeMap()");
        sb.AppendLine("   {");
        sb.AppendLine("        _typeMappings = new()");
        sb.AppendLine("        {");
        if (types != null)
        {
            foreach (var typeDto in types)
            {
                sb.AppendLine($"            {{ \"{typeDto.TypeId.Name}\", typeof(Rt{typeDto.TypeId.Name.MakeClassName()}) }},");
            }
        }
        sb.AppendLine("        };");

        sb.AppendLine("        _recordMappings = new()");
        sb.AppendLine("        {");
        if (records != null)
        {
            foreach (var ckRecordDto in records)
            {
                sb.AppendLine(
                    $"            {{ \"{ckRecordDto.RecordId.Name}\", typeof(Rt{ckRecordDto.RecordId.Name.MakeClassName()}Record) }},");
            }
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public CkModelId ModelId => new CkModelId(\"{ckModelId.FullName}\");");
        sb.AppendLine();
        sb.AppendLine("    public Type? GetCkTypeClass(CkTypeId ckTypeId)");
        sb.AppendLine("    {");
        sb.AppendLine("        _typeMappings.TryGetValue(ckTypeId, out var type);");
        sb.AppendLine("        return type;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public Type? GetCkRecordClass(CkRecordId ckRecordId)");
        sb.AppendLine("    {");
        sb.AppendLine("        _recordMappings.TryGetValue(ckRecordId, out var type);");
        sb.AppendLine("        return type;");
        sb.AppendLine("    }");        
        sb.AppendLine("}");

        return sb.ToString();
    }
}