using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

public class CkEmbeddedModelDiGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="CkEmbeddedModelGenerator" />
    /// </summary>
    public static readonly CkEmbeddedModelDiGenerator Instance = new();

    public string Generate(string ns, CkModelId ckModelId)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.ModelRepositories;");
        sb.AppendLine($"using {ns};");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            $"/// Extension methods for adding a embedded version of construction kit model {ckModelId.FullName} to the DI container.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine($"   public static IServiceCollection AddCkModel{ckModelId.ModelId.MakeClassName()}(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddTransient<ICkEmbeddedModel, {ckModelId.ModelId.MakeClassName()}CkEmbeddedModel>();");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}