using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

public class CkEmbeddedModelGenerator
{
    /// <summary>
    /// Returns the singleton instance of <see cref="CkEmbeddedModelGenerator"/>
    /// </summary>
    public static readonly CkEmbeddedModelGenerator Instance = new();

    public string Generate(string ns, string ckModelIdNs, CkModelId ckModelId)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects.Ck;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.ModelRepositories;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Represents a embedded version of construction kit model {ckModelId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public class {ckModelId.ModelId.MakeClassName()}CkEmbeddedModel : ICkEmbeddedModel");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine($"   private readonly ICkJsonSerializer _ckJsonSerializer;");
        sb.AppendLine();
        sb.AppendLine($"   public {ckModelId.ModelId.MakeClassName()}CkEmbeddedModel(ICkJsonSerializer ckJsonSerializer)");
        sb.AppendLine("    {");
        sb.AppendLine("        _ckJsonSerializer = ckJsonSerializer;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public CkModelId ModelId => new CkModelId(\"{ckModelId.FullName}\");");
        sb.AppendLine();
        sb.AppendLine("    public async Task<CkCompiledModelRoot> GetCompiledModelRootAsync(OperationResult operationResult)");
        sb.AppendLine("    {");
        sb.AppendLine("        var ckModelFileName = $\"ck-{ModelId.SemanticVersionedFullName.ToLower()}.json\";");
        sb.AppendLine($"        var ckModelNamespace = \"{ckModelIdNs}\";");
        sb.AppendLine("        var resourceName = $\"{ckModelNamespace}.{ckModelFileName}\";");
        sb.AppendLine();
        sb.AppendLine($"         using (var stream = typeof({ckModelId.ModelId.MakeClassName()}CkEmbeddedModel).Assembly.GetManifestResourceStream(resourceName))");
        sb.AppendLine("         {");
        sb.AppendLine("             if (stream == null)");
        sb.AppendLine("             {");
        sb.AppendLine("                  throw new KeyNotFoundException($\"'{resourceName}' not found in resources.\");");
        sb.AppendLine("             }");
        sb.AppendLine("             return await _ckJsonSerializer.DeserializeCompiledModelRootAsync(stream, operationResult);");
        sb.AppendLine("         }");
        sb.AppendLine("");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}