using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

internal class CkIdsCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="CkIdsCodeGenerator" />
    /// </summary>
    public static readonly CkIdsCodeGenerator Instance = new();

    public string Generate(string ns, CkModelId ckModelId, ICollection<CkCompiledTypeDto>? ckTypes,
        ICollection<CkAttributeDto>? ckAttributes, ICollection<CkAssociationRoleDto>? ckAssociationRoles)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit model {ckModelId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {ckModelId.Name.MakeClassName()}CkIds");
        sb.AppendLine("{");

        sb.AppendLine($"    public const string ModelIdName = \"{ckModelId.Name}\";");
        sb.AppendLine($"    public const string ModelIdVersion = \"{ckModelId.Version.ToString()}\";");
        sb.AppendLine(
            $"    public static readonly CkModelId CkModelId = new CkModelId(\"{ckModelId.Name}\", \"{ckModelId.Version}\");");

        if (ckTypes != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Types");

            foreach (var ckTypeDto in ckTypes.OrderBy(x => x.TypeId.Name))
            {
                sb.AppendLine(
                    $"    public static readonly RtCkId<CkTypeId> RtCk{ckTypeDto.TypeId.MakeClassName()}TypeId = new RtCkId<CkTypeId>(ModelIdName, \"{ckTypeDto.TypeId.FullName}\");");
                sb.AppendLine(
                    $"    public static readonly CkId<CkTypeId> Ck{ckTypeDto.TypeId.MakeClassName()}TypeId = new CkId<CkTypeId>(CkModelId, \"{ckTypeDto.TypeId.FullName}\");");
                sb.AppendLine(
                    $"    public const string RtCk{ckTypeDto.TypeId.MakeClassName()}TypeIdString = \"{ckModelId.Name}/{ckTypeDto.TypeId.FullName}\";");
            }
        }

        if (ckAttributes != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Attributes");

            foreach (var ckAttributeDto in ckAttributes.OrderBy(x => x.AttributeId.Name))
            {
                sb.AppendLine(
                    $"    public const string {ckAttributeDto.AttributeId.MakeClassName()}Attribute = \"{ckAttributeDto.AttributeId.SemanticVersionedFullName}\";");
            }
        }

        if (ckAssociationRoles != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Associations");

            foreach (var ckAssociationRoleDto in ckAssociationRoles.OrderBy(x => x.AssociationRoleId.RoleId))
            {
                sb.AppendLine(
                    $"    public static readonly RtCkId<CkAssociationRoleId> RtCk{ckAssociationRoleDto.AssociationRoleId.MakeClassName()}RoleId = new RtCkId<CkAssociationRoleId>(ModelIdName, \"{ckAssociationRoleDto.AssociationRoleId.FullName}\");");
            sb.AppendLine(
                $"    public static readonly CkId<CkAssociationRoleId> Ck{ckAssociationRoleDto.AssociationRoleId.MakeClassName()}RoleId = new CkId<CkAssociationRoleId>(CkModelId, \"{ckAssociationRoleDto.AssociationRoleId.FullName}\");");
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}