using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

internal class CkIdsCodeGenerator
{
    /// <summary>
    ///     <c>ChangePassword-1</c> → <c>ChangePassword</c>, <c>ChangePassword-2</c> → <c>ChangePassword2</c>.
    /// </summary>
    internal static string MakeMethodClassName(string methodId) => CkMethodIds.MethodClassName(methodId);

    /// <summary>
    ///     Returns the singleton instance of <see cref="CkIdsCodeGenerator" />
    /// </summary>
    public static readonly CkIdsCodeGenerator Instance = new();

    public string Generate(string ns, CkModelId ckModelId, ICollection<CkCompiledTypeDto>? ckTypes,
        ICollection<CkAttributeDto>? ckAttributes, ICollection<CkAssociationRoleDto>? ckAssociationRoles, ICollection<CkRecordDto>? ckRecords, ICollection<CkEnumDto>? ckEnums,
        ICollection<CkInterfaceDto>? ckInterfaces = null)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit model {ckModelId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {ckModelId.Name.MakeClassName()}CkIds");
        sb.AppendLine("{");

        sb.AppendLine($"    public const string ModelIdName = \"{ckModelId.Name}\";");
        sb.AppendLine($"    public const string ModelIdVersion = \"{ckModelId.Version.ToString()}\";");
        sb.AppendLine(
            $"    public static readonly CkModelId CkModelId = new CkModelId(\"{ckModelId.Name}\", \"{ckModelId.Version}\");");

        if (ckTypes != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Types");

            foreach (var ckTypeDto in ckTypes.OrderBy(x => x.TypeId.Name))
            {
                sb.AppendLine(
                    $"    public static readonly RtCkId<CkTypeId> RtCk{ckTypeDto.TypeId.MakeClassName()}TypeId = new RtCkId<CkTypeId>(ModelIdName, \"{ckTypeDto.TypeId.FullName}\");");
                sb.AppendLine(
                    $"    public static readonly CkId<CkTypeId> Ck{ckTypeDto.TypeId.MakeClassName()}TypeId = new CkId<CkTypeId>(CkModelId, \"{ckTypeDto.TypeId.FullName}\");");
                sb.AppendLine(
                    $"    public const string RtCk{ckTypeDto.TypeId.MakeClassName()}TypeIdString = \"{ckModelId.Name}/{ckTypeDto.TypeId.FullName}\";");
            }
        }

        if (ckAttributes != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Attributes");

            foreach (var ckAttributeDto in ckAttributes.OrderBy(x => x.AttributeId.Name))
            {
                sb.AppendLine(
                    $"    public const string {ckAttributeDto.AttributeId.MakeClassName()}Attribute = \"{ckAttributeDto.AttributeId.SemanticVersionedFullName}\";");
            }
        }

        if (ckAssociationRoles != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Associations");

            foreach (var ckAssociationRoleDto in ckAssociationRoles.OrderBy(x => x.AssociationRoleId.RoleId))
            {
                sb.AppendLine(
                    $"    public static readonly RtCkId<CkAssociationRoleId> RtCk{ckAssociationRoleDto.AssociationRoleId.MakeClassName()}RoleId = new RtCkId<CkAssociationRoleId>(ModelIdName, \"{ckAssociationRoleDto.AssociationRoleId.FullName}\");");
            sb.AppendLine(
                $"    public static readonly CkId<CkAssociationRoleId> Ck{ckAssociationRoleDto.AssociationRoleId.MakeClassName()}RoleId = new CkId<CkAssociationRoleId>(CkModelId, \"{ckAssociationRoleDto.AssociationRoleId.FullName}\");");
            }
        }

        if (ckRecords != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Records");

            foreach (var ckRecordDto in ckRecords.OrderBy(x => x.RecordId))
            {
                sb.AppendLine(
                    $"    public static readonly RtCkId<CkRecordId> RtCk{ckRecordDto.RecordId.MakeClassName()}RecordId = new RtCkId<CkRecordId>(ModelIdName, \"{ckRecordDto.RecordId.FullName}\");");
                sb.AppendLine(
                    $"    public static readonly CkId<CkRecordId> Ck{ckRecordDto.RecordId.MakeClassName()}RecordId = new CkId<CkRecordId>(CkModelId, \"{ckRecordDto.RecordId.FullName}\");");
            }
        }

        if (ckEnums != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Enums");

            foreach (var ckEnumDto in ckEnums.OrderBy(x => x.EnumId))
            {
                sb.AppendLine(
                    $"    public static readonly RtCkId<CkEnumId> RtCk{ckEnumDto.EnumId.MakeClassName()}EnumId = new RtCkId<CkEnumId>(ModelIdName, \"{ckEnumDto.EnumId.FullName}\");");
                sb.AppendLine(
                    $"    public static readonly CkId<CkEnumId> Ck{ckEnumDto.EnumId.MakeClassName()}EnumId = new CkId<CkEnumId>(CkModelId, \"{ckEnumDto.EnumId.FullName}\");");
            }
        }

        // CK v2 (AB#5667): interface ids. The generated class stays flat.
        if (ckInterfaces is { Count: > 0 })
        {
            sb.AppendLine();
            sb.AppendLine("    // Interfaces");

            foreach (var ckInterfaceDto in ckInterfaces.OrderBy(x => x.InterfaceId))
            {
                var name = ckInterfaceDto.InterfaceId.MakeClassName();
                sb.AppendLine(
                    $"    public static readonly RtCkId<CkInterfaceId> RtCk{name}InterfaceId = new RtCkId<CkInterfaceId>(ModelIdName, \"{ckInterfaceDto.InterfaceId.FullName}\");");
                sb.AppendLine(
                    $"    public static readonly CkId<CkInterfaceId> Ck{name}InterfaceId = new CkId<CkInterfaceId>(CkModelId, \"{ckInterfaceDto.InterfaceId.FullName}\");");
                sb.AppendLine(
                    $"    public const string RtCk{name}InterfaceIdString = \"{ckModelId.Name}/{ckInterfaceDto.InterfaceId.FullName}\";");
            }
        }

        // CK v2 (AB#5669): qualified method ids of the methods DECLARED by the model's types, e.g.
        // UserChangePasswordMethodId = "System.Identity/User.ChangePassword-1" (method version > 1 is appended).
        var methods = (ckTypes ?? [])
            .SelectMany(t => (t.Methods ?? []).Select(m => (Type: t, Method: m)))
            .OrderBy(x => x.Type.TypeId.Name).ThenBy(x => x.Method.MethodId)
            .ToList();
        if (methods.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    // Methods");

            foreach (var (ckType, method) in methods)
            {
                var qualified = CkMethodIds.Qualify(new RtCkId<CkTypeId>(ckModelId.Name, ckType.TypeId), method.MethodId);
                sb.AppendLine(
                    $"    public const string {ckType.TypeId.MakeClassName()}{MakeMethodClassName(method.MethodId)}MethodId = \"{qualified}\";");
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}