using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.DependencyGraph;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

/// <summary>
///     CK v2 (F1.4-S1, AB#5918): emits <c>public partial interface IRt&lt;Name&gt;</c> for a CK interface — attribute
///     members as get-only properties with the same CLR types as on the Rt classes (nullable when the member is
///     optional), <c>extends</c> as C# interface inheritance. Association members are omitted: the Rt classes have
///     no generated navigations yet. Generated Rt classes implement their declared interfaces explicitly
///     (<see cref="GenerateExplicitImplementations" />), so a type that assigns an optional member as required still
///     conforms.
/// </summary>
public static class CkInterfaceCodeGenerator
{
    /// <summary>The C# interface name of a CK interface: <c>Named-1</c> → <c>IRtNamed</c>, <c>Named-2</c> → <c>IRtNamed2</c>.</summary>
    public static string InterfaceName(CkInterfaceId ckInterfaceId) => $"IRt{ckInterfaceId.MakeClassName()}";

    /// <summary>Generates the interface source.</summary>
    public static string Generate(string ns, CkModelId modelId, CkInterfaceDto ckInterface, string cacheTenantId,
        ICkCacheService cacheService)
    {
        var interfaceGraph = cacheService.GetRtCkInterface(cacheTenantId,
            new RtCkId<CkInterfaceId>(modelId.Name, ckInterface.InterfaceId));
        var bases = interfaceGraph.DeclaredExtends.Select(e => InterfaceName(e.ElementId)).ToList();
        // A member repeated identically from a parent would hide it (CS0108); the parent already declares it.
        var inherited = new HashSet<CkId<CkAttributeId>>(interfaceGraph.AllExtendedInterfaces
            .SelectMany(e => cacheService.GetRtCkInterface(cacheTenantId, e.ToRtCkId()).Attributes.Keys));

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.Geospatial.Geometry;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.RepositoryEntities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit interface {ckInterface.InterfaceId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial interface {InterfaceName(ckInterface.InterfaceId)}" +
                      (bases.Count == 0 ? "" : " : " + string.Join(", ", bases)));
        sb.AppendLine("{");
        foreach (var member in interfaceGraph.Attributes.Values.Where(m => !inherited.Contains(m.CkAttributeId))
                     .OrderBy(m => m.AttributeName, StringComparer.Ordinal))
        {
            var type = PropertyType(member, cacheTenantId, cacheService);
            if (type != null)
            {
                sb.AppendLine($"  {type} {member.AttributeName} {{ get; }}");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    ///     Explicit implementations of every attribute member of the declared interfaces and their parents, for the Rt
    ///     class of a type: <c>string IRtNamed.Name => Name;</c>; an optional member the type does not assign returns
    ///     <c>default</c>.
    /// </summary>
    public static void GenerateExplicitImplementations(StringBuilder sb, CkTypeGraph typeGraph,
        IEnumerable<CkId<CkInterfaceId>> declared, string cacheTenantId, ICkCacheService cacheService)
    {
        var emitted = new HashSet<(CkId<CkInterfaceId>, string)>();
        foreach (var ckInterfaceId in declared)
        {
            var graph = cacheService.GetRtCkInterface(cacheTenantId, ckInterfaceId.ToRtCkId());
            foreach (var levelId in new[] { graph.CkInterfaceId }.Concat(graph.AllExtendedInterfaces))
            {
                var level = levelId == graph.CkInterfaceId
                    ? graph
                    : cacheService.GetRtCkInterface(cacheTenantId, levelId.ToRtCkId());
                var levelInherited = new HashSet<CkId<CkAttributeId>>(level.AllExtendedInterfaces
                    .SelectMany(e => cacheService.GetRtCkInterface(cacheTenantId, e.ToRtCkId()).Attributes.Keys));
                foreach (var member in level.Attributes.Values.Where(m => !levelInherited.Contains(m.CkAttributeId))
                             .OrderBy(m => m.AttributeName, StringComparer.Ordinal))
                {
                    if (!emitted.Add((level.CkInterfaceId, member.AttributeName)))
                    {
                        continue;
                    }

                    var type = PropertyType(member, cacheTenantId, cacheService);
                    if (type != null)
                    {
                        // An optional member the type does not assign has no property: it reads as null.
                        var body = typeGraph.AllAttributes.ContainsKey(member.CkAttributeId)
                            ? member.AttributeName
                            : "default";
                        sb.AppendLine(
                            $"  {type} {InterfaceName(level.CkInterfaceId.ElementId)}.{member.AttributeName} => {body};");
                    }
                }
            }
        }
    }

    /// <summary>
    ///     The CLR type of a member — taken from the property the attribute generator emits, so it is identical to
    ///     the Rt class property by construction.
    /// </summary>
    private static string? PropertyType(CkTypeAttributeGraph member, string cacheTenantId, ICkCacheService cacheService)
    {
        var attributeGraph = cacheService.GetCkAttribute(cacheTenantId, member.CkAttributeId);
        var dto = new CkTypeAttributeDto
        {
            CkAttributeId = member.CkAttributeId, AttributeName = member.AttributeName, IsOptional = member.IsOptional
        };
        var property = new StringBuilder();
        if (member.IsOptional)
        {
            AttributeCodeGenerator.GenerateNullableProperty(dto, property, attributeGraph);
        }
        else
        {
            AttributeCodeGenerator.GenerateNonNullableProperty(dto, property, attributeGraph);
        }

        const string prefix = "  public ";
        var firstLine = property.ToString().Split('\n').FirstOrDefault(l => l.StartsWith(prefix, StringComparison.Ordinal));
        var suffix = " " + member.AttributeName;
        if (firstLine == null)
        {
            return null;
        }

        firstLine = firstLine.TrimEnd('\r');
        return firstLine.EndsWith(suffix, StringComparison.Ordinal)
            ? firstLine.Substring(prefix.Length, firstLine.Length - prefix.Length - suffix.Length)
            : null;
    }
}
