using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

/// <summary>
///     CK v2 (F1.4-S2, AB#5919): typed contracts for the methods a type declares — definitions only, no dispatch.
///     Per method <c>{Type}{Method}Parameters</c> (required parameters are <c>required</c>, optional ones nullable;
///     camelCase parameter names become PascalCase properties) and, when the method has a result,
///     <c>{Type}{Method}Result</c> with a <c>Value</c>. Sensitive parameters are redacted (<c>***</c>) by
///     <c>ToString()</c>. Names come from <see cref="CkMethodIds.GeneratedName" /> (unique per model, message 125).
/// </summary>
public static class CkMethodCodeGenerator
{
    /// <summary>Generates the parameter and result records of every method declared by the type.</summary>
    public static string Generate(string ns, CkTypeDto ckType)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.RepositoryEntities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");

        foreach (var method in ckType.Methods ?? [])
        {
            var name = CkMethodIds.GeneratedName(ckType.TypeId, method.MethodId);
            var parameters = method.Parameters ?? [];

            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Parameters of method {method.MethodId} of construction kit type {ckType.TypeId.FullName}");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public sealed partial record {name}Parameters");
            sb.AppendLine("{");
            foreach (var parameter in parameters)
            {
                if (!string.IsNullOrWhiteSpace(parameter.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {parameter.Description}");
                    sb.AppendLine("  /// </summary>");
                }

                var type = ClrType(parameter.ValueType, parameter.ValueCkRecordId, parameter.ValueCkEnumId);
                sb.AppendLine(parameter.IsOptional
                    ? $"  public {type}? {PropertyName(parameter.Name)} {{ get; init; }}"
                    : $"  public required {type} {PropertyName(parameter.Name)} {{ get; init; }}");
            }

            sb.AppendLine();
            sb.AppendLine("  /// <summary>Renders the parameters; sensitive values are redacted.</summary>");
            var rendered = string.Join(", ", parameters.Select(p =>
                $"{PropertyName(p.Name)} = " + (p.Sensitive ? "***" : $"{{{PropertyName(p.Name)}}}")));
            sb.AppendLine(
                $"  public override string ToString() => $\"{name}Parameters {{{{ {rendered.Replace("\"", "\\\"")} }}}}\";");
            sb.AppendLine("}");

            if (method.Result != null)
            {
                sb.AppendLine();
                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// Result of method {method.MethodId} of construction kit type {ckType.TypeId.FullName}");
                sb.AppendLine("/// </summary>");
                sb.AppendLine($"public sealed partial record {name}Result");
                sb.AppendLine("{");
                sb.AppendLine(
                    $"  public {ClrType(method.Result.ValueType, method.Result.ValueCkRecordId, method.Result.ValueCkEnumId)}? Value {{ get; init; }}");
                sb.AppendLine("}");
            }
        }

        return sb.ToString();
    }

    /// <summary><c>newPassword</c> → <c>NewPassword</c>.</summary>
    internal static string PropertyName(string parameterName) =>
        parameterName.Length == 0 ? parameterName : char.ToUpperInvariant(parameterName[0]) + parameterName.Substring(1);

    private static string ClrType(AttributeValueTypesDto valueType, CkId<CkRecordId>? recordId, CkId<CkEnumId>? enumId) =>
        valueType switch
        {
            AttributeValueTypesDto.String => "string",
            AttributeValueTypesDto.Boolean => "bool",
            AttributeValueTypesDto.DateTime => "global::System.DateTime",
            AttributeValueTypesDto.DateTimeOffset => "global::System.DateTimeOffset",
            AttributeValueTypesDto.TimeSpan => "global::System.TimeSpan",
            AttributeValueTypesDto.Int => "int",
            AttributeValueTypesDto.Int64 => "long",
            AttributeValueTypesDto.Double => "double",
            AttributeValueTypesDto.StringArray => "global::System.Collections.Generic.IReadOnlyList<string>",
            AttributeValueTypesDto.IntArray => "global::System.Collections.Generic.IReadOnlyList<long>",
            AttributeValueTypesDto.Enum when enumId != null => $"Rt{enumId.ElementId.Name.MakeClassName()}Enum",
            AttributeValueTypesDto.Record when recordId != null => $"Rt{recordId.ElementId.Name.MakeClassName()}Record",
            _ => "object"
        };
}
