using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects.Ck;
using Meshmakers.Octo.ConstructionKit.Contracts.DependencyGraph;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

/// <summary>
/// Generates code for a CK type
/// </summary>
public class CkRecordCodeGenerator
{
    /// <summary>
    /// Returns the singleton instance of <see cref="CkRecordCodeGenerator"/>
    /// </summary>
    public static readonly CkRecordCodeGenerator Instance = new();

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is CkRecordCodeGenerator;
    }

    public bool Equals(CkRecordCodeGenerator? other)
    {
        return other is CkRecordCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode() => GetType().GetHashCode();

    public string Generate(string ns, CkModelId modelId, CkRecordDto ckRecord, string cacheTenantId, ICkCacheService cacheService)
    {
        var ckBaseType = " : RtRecord";
        if (ckRecord.DerivedFromCkRecordId != null)
        {
            ckBaseType = $" : Rt{ckRecord.DerivedFromCkRecordId.Value.ModelId.ModelId.MakeClassName()}" +
                         $"{ckRecord.DerivedFromCkRecordId.Value.Key.RecordId.MakeClassName()}Record";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit type {ckRecord.RecordId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{modelId.ModelId.MakeClassName()}{ckRecord.RecordId.RecordId.MakeClassName()}Record{ckBaseType}");
        sb.AppendLine("{");
        if (ckRecord.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckRecord.Attributes)
            {
                CkAttributeGraph ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }
                
                if (ckAttributeGraph.IsOptional)
                {
                    AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
                else
                {
                    AttributeCodeGenerator.GenerateNonNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

   
}