using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

/// <summary>
///     Generates code for a CK type
/// </summary>
public class CkTypeCodeGenerator : ICkTypeCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="CkTypeCodeGenerator" />
    /// </summary>
    public static readonly CkTypeCodeGenerator Instance = new();

    /// <inheritdoc />
    public bool Equals(ICkTypeCodeGenerator? other)
    {
        return other is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public string Generate(string ns, CkModelId modelId, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
        => Generate(ns, modelId, ckType, cacheTenantId, cacheService, 1);

    /// <summary>
    ///     Generates the Rt class of a type. F1.4-S2: for a <c>ckLanguage: 2</c> model the class is <c>sealed</c> for
    ///     <c>isFinal</c> or for <c>derivable: Model</c> without a subtype in its own model; v1 output is unchanged.
    ///     <c>isAbstract</c> does not emit <c>abstract</c> (repository generics need <c>new()</c>; review G3 E-M3,
    ///     revisit in Phase 4).
    /// </summary>
    public string Generate(string ns, CkModelId modelId, CkTypeDto ckType, string cacheTenantId,
        ICkCacheService cacheService, int ckLanguage)
    {
        string ckBaseType;
        if (ckType.DerivedFromCkTypeId != null)
        {
            ckBaseType = $" : Rt" +
                         $"{ckType.DerivedFromCkTypeId.ElementId.MakeClassName()}";
        }
        else
        {
            ckBaseType = ": Meshmakers.Octo.SystematizedData.Persistence.DatabaseEntities.RtEntity";
        }

        // CK v2 (F1.4-S1): the declared interfaces (inherited ones come with the base class / C# interface inheritance).
        var implements = ckType.Implements ?? [];
        if (implements.Count > 0)
        {
            ckBaseType += (ckBaseType.TrimStart().StartsWith(":") ? ", " : " : ") +
                          string.Join(", ", implements.Select(i => CkInterfaceCodeGenerator.InterfaceName(i.ElementId)));
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.Geospatial.Geometry;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.RepositoryEntities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit type {ckType.TypeId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine(
            $"[RtCkId({modelId.Name.MakeClassName()}CkIds.RtCk{ckType.TypeId.MakeClassName()}TypeIdString)]");
        sb.AppendLine($"public {ClassModifier(modelId, ckType, cacheTenantId, cacheService, ckLanguage)}partial class Rt{ckType.TypeId.MakeClassName()}{ckBaseType}");
        sb.AppendLine("{");
        if (ckType.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckType.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }

                if (ckTypeAttributeDto.IsOptional)
                {
                    AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
                else
                {
                    AttributeCodeGenerator.GenerateNonNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
            }
        }

        if (ckType.Associations != null)
        {
            foreach (var ckTypeAssociationDto in ckType.Associations)
            {
                GenerateNavigation(ckTypeAssociationDto, sb, cacheTenantId, cacheService);
            }
        }

        if (implements.Count > 0)
        {
            var typeGraph = cacheService.GetRtCkType(cacheTenantId, new RtCkId<CkTypeId>(modelId.Name, ckType.TypeId));
            CkInterfaceCodeGenerator.GenerateExplicitImplementations(sb, typeGraph, implements, cacheTenantId,
                cacheService);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ClassModifier(CkModelId modelId, CkTypeDto ckType, string cacheTenantId,
        ICkCacheService cacheService, int ckLanguage)
    {
        if (ckLanguage < 2)
        {
            return "";
        }

        // Review G3 E-M3 (platform-owner decision): isAbstract does NOT emit `abstract` — the repository generics
        // require `new()` (GetRtEntitiesByTypeAsync<TEntity> etc.), so an abstract Rt class could not be queried.
        // Revisit in Phase 4. An abstract type is never sealed either.
        if (ckType.IsAbstract)
        {
            return "";
        }

        if (ckType.IsFinal)
        {
            return "sealed ";
        }

        var typeGraph = cacheService.GetRtCkType(cacheTenantId, new RtCkId<CkTypeId>(modelId.Name, ckType.TypeId));
        var hasInModelSubtype = typeGraph.GetAllDerivedTypes(false).Any(d => d.ModelId.Name == modelId.Name);
        return typeGraph.Derivable == CkDerivableDto.Model && !hasInModelSubtype ? "sealed " : "";
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return GetType().GetHashCode();
    }

    private void GenerateNavigation(CkTypeAssociationDto ckTypeAssociationDto, StringBuilder sb, string cacheTenantId,
        ICkCacheService cacheService)
    {
        //var ckAssociationRoleGraph = cacheService.GetCkAssociationRole(cacheTenantId, ckTypeAssociationDto.CkRoleId);

        sb.AppendLine($"  // Unsupported by Generator: {ckTypeAssociationDto.CkRoleId}->{ckTypeAssociationDto.TargetCkTypeId}");
    }
}