using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.ConstructionKit.SourceGeneration;

/// <summary>
///     Generates code for a CK type
/// </summary>
public class CkTypeCodeGenerator : ICkTypeCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="CkTypeCodeGenerator" />
    /// </summary>
    public static readonly CkTypeCodeGenerator Instance = new();

    /// <inheritdoc />
    public bool Equals(ICkTypeCodeGenerator? other)
    {
        return other is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public string Generate(string ns, CkModelId modelId, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckBaseType;
        if (ckType.DerivedFromCkTypeId != null)
        {
            ckBaseType = $" : Rt" +
                         $"{ckType.DerivedFromCkTypeId.ElementId.MakeClassName()}";
        }
        else
        {
            ckBaseType = ": Meshmakers.Octo.SystematizedData.Persistence.DatabaseEntities.RtEntity";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.Geospatial.Geometry;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.RepositoryEntities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit type {ckType.TypeId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine(
            $"[RtCkId({modelId.Name.MakeClassName()}CkIds.RtCk{ckType.TypeId.MakeClassName()}TypeIdString)]");
        sb.AppendLine($"public partial class Rt{ckType.TypeId.MakeClassName()}{ckBaseType}");
        sb.AppendLine("{");
        if (ckType.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckType.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }

                if (ckTypeAttributeDto.IsOptional)
                {
                    AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
                else
                {
                    AttributeCodeGenerator.GenerateNonNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
            }
        }

        if (ckType.Associations != null)
        {
            foreach (var ckTypeAssociationDto in ckType.Associations)
            {
                GenerateNavigation(ckTypeAssociationDto, sb, cacheTenantId, cacheService);
            }
        }

        sb.AppendLine("}");

        // Emit Sd{CkType} : StreamDataEntity only when at least one attribute is a data-stream attribute.
        if (ckType.Attributes != null)
        {
            var dataStreamAttributes = ckType.Attributes
                .Select(a => (Dto: a, Graph: cacheService.GetCkAttribute(cacheTenantId, a.CkAttributeId)))
                .Where(x => x.Graph.IsDataStream)
                .ToList();

            if (dataStreamAttributes.Count > 0)
            {
                var typeName = ckType.TypeId.MakeClassName();
                sb.AppendLine();
                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// Stream-data projection generated from construction kit type {ckType.TypeId.FullName}");
                sb.AppendLine("/// </summary>");
                sb.AppendLine($"public partial class Sd{typeName} : Meshmakers.Octo.Runtime.Contracts.StreamData.StreamDataEntity");
                sb.AppendLine("{");
                foreach (var (dto, graph) in dataStreamAttributes)
                {
                    if (!string.IsNullOrWhiteSpace(graph.Description))
                    {
                        sb.AppendLine("  /// <summary>");
                        sb.AppendLine($"  /// {graph.Description}");
                        sb.AppendLine("  /// </summary>");
                    }

                    AttributeCodeGenerator.GenerateNullableProperty(dto, sb, graph);
                }

                sb.AppendLine("}");
            }
        }

        return sb.ToString();
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return GetType().GetHashCode();
    }

    private void GenerateNavigation(CkTypeAssociationDto ckTypeAssociationDto, StringBuilder sb, string cacheTenantId,
        ICkCacheService cacheService)
    {
        //var ckAssociationRoleGraph = cacheService.GetCkAssociationRole(cacheTenantId, ckTypeAssociationDto.CkRoleId);

        sb.AppendLine($"  // Unsupported by Generator: {ckTypeAssociationDto.CkRoleId}->{ckTypeAssociationDto.TargetCkTypeId}");
    }
}