//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meshmakers.Octo.ConstructionKit.Engine {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Meshmakers.Octo.ConstructionKit.Engine.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        internal static string DefaultValues {
            get {
                return ResourceManager.GetString("DefaultValues", resourceCulture);
            }
        }
        
        internal static string IsDataStream {
            get {
                return ResourceManager.GetString("IsDataStream", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string CkEnumId_CkRecordId {
            get {
                return ResourceManager.GetString("CkEnumId/CkRecordId", resourceCulture);
            }
        }
        
        internal static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        internal static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        internal static string DefinedAttributes {
            get {
                return ResourceManager.GetString("DefinedAttributes", resourceCulture);
            }
        }
        
        internal static string IsOptional {
            get {
                return ResourceManager.GetString("IsOptional", resourceCulture);
            }
        }
        
        internal static string AutoIncrementReference {
            get {
                return ResourceManager.GetString("AutoIncrementReference", resourceCulture);
            }
        }
        
        internal static string InboundMultiplicity {
            get {
                return ResourceManager.GetString("InboundMultiplicity", resourceCulture);
            }
        }
        
        internal static string InboundName {
            get {
                return ResourceManager.GetString("InboundName", resourceCulture);
            }
        }
        
        internal static string OutboundMultiplicity {
            get {
                return ResourceManager.GetString("OutboundMultiplicity", resourceCulture);
            }
        }
        
        internal static string OutboundName {
            get {
                return ResourceManager.GetString("OutboundName", resourceCulture);
            }
        }
        
        internal static string TargetCKTypeID {
            get {
                return ResourceManager.GetString("TargetCKTypeID", resourceCulture);
            }
        }
        
        internal static string TargetAttributes {
            get {
                return ResourceManager.GetString("TargetAttributes", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string AutoCompleteValues {
            get {
                return ResourceManager.GetString("AutoCompleteValues", resourceCulture);
            }
        }
        
        internal static string CKAttributeID {
            get {
                return ResourceManager.GetString("CKAttributeID", resourceCulture);
            }
        }
        
        internal static string LinkHelpers_GetGeneratedFilePath_Document_path_cannot_be_empty {
            get {
                return ResourceManager.GetString("LinkHelpers_GetGeneratedFilePath_Document_path_cannot_be_empty", resourceCulture);
            }
        }
        
        internal static string LinkHelpers_GetGeneratedFilePath_Extension_cannot_be_empty {
            get {
                return ResourceManager.GetString("LinkHelpers_GetGeneratedFilePath_Extension_cannot_be_empty", resourceCulture);
            }
        }
        
        internal static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
    }
}
