"$schema": "https://schemas.meshmakers.cloud/construction-kit-elements.schema.json"
types:
  - typeId: Configuration
    derivedFromCkTypeId: ${thisModel}/Entity
    isFinal: false
    isAbstract: true
  - typeId: TenantConfiguration
    derivedFromCkTypeId: ${thisModel}/Configuration
    isFinal: true
    isAbstract: false
    attributes:
      - id: ${thisModel}/ConfigurationValue
        name: ConfigurationValue
        isOptional: true